# Generated by Django 5.2.6 on 2025-10-02 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='總金額')),
                ('payment_method', models.CharField(choices=[('credit_card', '信用卡'), ('line_pay', 'Line Pay'), ('cash', '貨到付款')], max_length=50, verbose_name='付款方式')),
                ('payment_status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('failed', '付款失敗'), ('refunded', '已退款')], default='pending', max_length=50, verbose_name='付款狀態')),
                ('shipping_method', models.CharField(choices=[('home_delivery', '宅配'), ('convenience_store', '超商取貨')], max_length=50, verbose_name='運送方式')),
                ('shipping_status', models.CharField(choices=[('preparing', '備貨中'), ('shipped', '已出貨'), ('delivered', '已送達'), ('returned', '已退貨')], default='preparing', max_length=50, verbose_name='運送狀態')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='收件人姓名')),
                ('receiver_phone', models.CharField(max_length=15, verbose_name='收件人電話')),
                ('receiver_address', models.CharField(max_length=255, verbose_name='收件地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon', verbose_name='優惠券')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user', verbose_name='顧客')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'ordering': ['-created_at'],
            },
        ),
    ]
