# Generated by Django 5.2.6 on 2025-10-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='產品名稱')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='價格')),
                ('stock', models.PositiveIntegerField(verbose_name='庫存量')),
                ('attribute', models.CharField(blank=True, choices=[('frozen', '冷凍'), ('refrigeration', '冷藏'), ('room_temperature', '常溫')], max_length=100, verbose_name='產品屬性')),
                ('expiration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='保存天數')),
                ('image_url', models.URLField(blank=True, verbose_name='產品圖片 URL')),
                ('description', models.TextField(blank=True, verbose_name='產品描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '產品',
                'verbose_name_plural': '產品',
            },
        ),
    ]
