# Generated by Django 5.2.6 on 2025-10-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', '待付款'), ('success', '已付款'), ('failed', '付款失敗'), ('refunded', '已退款')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '付款',
                'verbose_name_plural': '付款',
                'ordering': ['-created_at'],
            },
        ),
    ]
