# Generated by Django 5.2.6 on 2025-10-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('tracking_number', models.CharField(max_length=100)),
                ('carrier', models.CharField(choices=[('BlackCat', '黑貓'), ('FamilyMart', '全家'), ('7-11', '7-11'), ('HiLife', '萊爾富'), ('ChunghwaPost', '中華郵政'), ('Other', '其他')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '待運送'), ('in_transit', '運送中'), ('delivered', '已送達'), ('returned', '已退回'), ('cancelled', '已取消')], max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '物流狀況',
                'verbose_name_plural': '物流狀況',
                'ordering': ['-created_at'],
            },
        ),
    ]
