# Generated by Django 5.2.6 on 2025-10-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipment_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='tracking_number',
        ),
    ]
