# Generated by Django 5.2.6 on 2025-10-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', '打折'), ('fixed', '固定金額')], max_length=10)),
                ('discount_value', models.IntegerField()),
                ('min_order_amount', models.IntegerField()),
                ('usage_limit', models.IntegerField()),
                ('used_count', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '優惠券',
                'verbose_name_plural': '優惠券',
                'ordering': ['-created_at'],
            },
        ),
    ]
