# Generated by Django 5.2.6 on 2025-09-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100, unique=True, verbose_name='帳號')),
                ('password_hash', models.CharField(max_length=255, verbose_name='密碼雜湊')),
                ('username', models.CharField(max_length=100, verbose_name='使用者名稱')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子郵件')),
                ('phone', models.CharField(max_length=20, verbose_name='手機號碼')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', '其他')], max_length=10, verbose_name='性別')),
                ('role', models.CharField(choices=[('customer', '顧客'), ('admin', '管理員')], default='customer', max_length=10, verbose_name='角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
            },
        ),
    ]
